version: "3.3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "mariadb-volume:/var/lib/mysql/"
      - "./assignments/hw6/my.cnf:/etc/mysql/conf.d/my.cnf"
    networks:
      - hw6-net

  final-project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: final-project
    restart: "no"
    ports:
      - "5001:8080"
    depends_on:
      - mariadb
    volumes:
      - "./docker-output:/app/output/"
    command:
      [
        "/scripts/wait-for-it.sh",
        "mariadb:3306",
        "--",
        "bash",
        "/scripts/run.sh",
      ]
    networks:
      - hw6-net

networks:
  hw6-net:

volumes:
  mariadb-volume:
