version: "3.3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "mariadb-volume:/var/lib/mysql/"
      - "./assignments/hw6/my.cnf:/etc/mysql/conf.d/my.cnf"
    networks:
      - hw6-net

  hw6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw6
    restart: "no"
    ports:
      - "5001:8080"
    depends_on:
      - mariadb
    volumes:
      - "./assignments/hw6/scripts/run.sh:/scripts/run.sh"
      - "./assignments/hw6/scripts/wait-for-it.sh:/scripts/await.sh"
      - "./assignments/hw6/scripts/pitcher.sql:/scripts/pitcher.sql"
      - "./assignments/hw5:/hw5"
      - "./baseball.sql:/data/baseball.sql"
      - "./docker-output:/app/output/"
    command:
      ["/scripts/await.sh", "mariadb:3306", "--", "bash", "/scripts/run.sh"]
    networks:
      - hw6-net

networks:
  hw6-net:

volumes:
  mariadb-volume:
